extra_css:
  - stylesheets/IoT-FS.css
extra:
  generator: false
  version:
    provider: mike
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - fenced_code
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      marker: ''
      permalink: true
      toc_depth: 3
  - wikilinks
nav:
  - Home: index.md
  - 'Getting Started':
    - Introduction: getting-started/index.md
    - Infrastructure: getting-started/infrastructure.md
    - Understanding MQTT: getting-started/mqtt.md
  - Infrastructure: 
    - Introduction to Infrastructure: infrastructure/index.md
    - 'Linux Server': infrastructure/server-linux.md
    - Docker:
      - 'Docker Server': infrastructure/docker.md
      - 'Docker Compose': infrastructure/docker-compose.md
      - 'Docker Deploy': infrastructure/docker-deploy.md
      - 'Kubernetes': infrastructure/docker-kubernetes.md
plugins:
  - search:
      prebuild_index: true
      separator: '[\s\-\_]+'
repo_name: clueboard/IoT-FS
repo_url: https://github.com/clueboard/IoT-FS
site_name: Internet of Things - From Scratch!
site_url: https://IoT-FS.clueboard.co/
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Raleway
    code: Overpass Mono
  icon:
    repo: fontawesome/brands/github
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
