# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Update Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  devel_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure git
      run: |
        git config --local user.email "skullydazed@gmail.com"
        git config --local user.name "Zach White"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel 
        pip install -r requirements.txt

    - name: Update docs
      run: mkdocs gh-deploy --force
